# Generated by Django 3.2.7 on 2021-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('img', models.ImageField(null=True, upload_to='img/')),
                ('position', models.CharField(max_length=60)),
                ('profile', models.TextField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
